# Default Rules인 규칙을 비활성화시키기
disabled_rules:

#    # 라인 뒤에 공백이 없어야 합니다. https://realm.github.io/SwiftLint/trailing_whitespace.html
#    - trailing_whitespace
#
#    # 강제 캐스팅은 피해야합니다. https://realm.github.io/SwiftLint/force_cast.html
#    - force_cast
#
#    # 강제 언래핑은 피해야합니다. https://realm.github.io/SwiftLint/force_unwrapping.html
#   - force_unwrapping
    - unused_optional_binding
    - line_length
    - todo
    - file_length
    - function_body_length
    - type_body_length

# Default가 비활성화인 규칙을 활성화시키기
opt_in_rules:
    # .count==0 보다는 .isEmpty를 사용하는 것이 좋습니다. https://realm.github.io/SwiftLint/empty_count.html
    - empty_count

    # 빈 String 문자열과 비교하는 것 보다는 .isEmpty를 사용하는 것이 좋습니다. https://realm.github.io/SwiftLint/empty_string.html
#    - empty_string

# Lint 검사에서 포함시키고 싶은 항목
included:

# Lint 검사에서 제외하고 싶은 항목
excluded:
    - Pods
    - SwiftUITemplateTests
    - SwiftUITemplateUITests

# 한 줄로는 warning의 수준만 설정할 수 있습니다.
